language: node_js
node_js:
  - "14"

cache:
  directories:
    - node_modules

services:
  - redis-server

install:
  - npm ci

before_script:
  - cp .env.example .env
  - export $(grep -v '^#' .env | xargs)


