name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          cp .env.example .env
          export $(grep -v '^#' .env | xargs)

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm test

      - name: Build
        run: npm run build
