global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "naturants_node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "naturants_app"
    static_configs:
      - targets: ["docker.for.mac.host.internal:8080"]
